stage: dev
public_bucket_name: ephemera-public-sammartin-${self:custom.config.stage}
dynamodb_table_name: ephemera-${self:custom.config.stage}
region: eu-west-2
max_secret_age_hours: "24"

# Provide a list of IP addresses to which Ephemera will be restricted (i.e. Your corporate office egress IP)
# The default of 0.0.0.0/0 permits access from any host on the internet
whitelisted_ips:
  - 0.0.0.0/0

# These settings enable HTTPS for the front-end Ephemera UI by fronting the S3 bucket with AWS CloudFront. The UI uses HTTP by default.
# Pre-requsites:
# - Create or import an SSL Certificate into the `us-east-1` (N. Virginia) Region - https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html
# - Add the `Identifier` of the ACM Certificate (Not the full ARN) below
use_https_ui: false
acm_certificate_id: undefined
