stage: dev1
public_bucket_name: ephemera-public-${self:custom.config.stage}-local
client:
    public_bucket_name: ephemera-public-${self:custom.config.stage}-local
dynamodb_table_name: ephemera-${self:custom.config.stage}-local
region: us-west-2
max_secret_age_hours: "24"
